siteName: Seven Kings Web Design, Kingston
title: Seven Kings Web Design | Web Development, SEO
author: David White
url: https://github.com/webdigga/seven-kings
poweredBy: Seven Kings Web Design
description: Seven Kings Web Design, web development, SEO and performance services in the UK. Elevate your online presence with responsive, user-friendly websites
type: website
logoAlt: Seven Kings Web Design Logo
email: david@sevenkingswebdesign.co.uk
phoneNumber: "07877304672"
companyNumber: "15653819"
logoUrl: /_includes/static/img/logo.webp
seoName: Seven Kings Web Design
streetAddress: 23 Carisbrooke House, Royal Quarter, Seven Kings Way
townCity: Kingston Upon Thames
country: GB
region: London
postCode: KT2 5BS
weekDayOpening: 09:00
weekDayClosing: 17:00
